### PR TITLE
Add support for caching (with Rails)

### PR DESCRIPTION
**Pull request by stefanoc**
This PR introduces a basic caching support if Rails is defined. The right version of the instance method ``tor?`` is defined in the middleware class at load time to minimize the amount of runtime checks.
I've also tried to avoid some potentially unnecessary object allocations.

/cc @andreacfm @openmosix

### CODE REVIEW

**Comment by andreacfm** [comment]
@openmosix @taganaka 
This worth to be tested IMHO. The address resolver is experiencing some serious lag recently. From new relic we noticed the middleware is taking randomly up to 1-2 seconds.

**Comment by openmosix** [comment]
@andreacfm @stefanoc that's kind of odd, because the DNS resolver should have a local cache - after hitting it the first time, the resolv cache should be warm and the other requests be kind of super quick. 
Any idea on how to test this vs without it? (we can test it locally, the rack stack enables it only in prod/staging, but we can activate it for dev too)

**Comment by andreacfm** [comment]
@openmosix yes it is odd but the newrelic tracking was really clear today in pointing this middleware as consuming up to several seconds for request.
I added the middleware in integration using api locally on 4100. Perfomance decrease by at least 50%. With the caching the performance are back to normal. Btw I am not sure if testing on localhost makes any sense.

**Comment by openmosix** [comment]
@andreacfm shall I build a new gem version, push it to api, send it to prod and see if new relic notices an improvement?

**Comment by andreacfm** [comment]
@openmosix to make a spike you can even deploy pointing to the @stefanoc branch.

**Comment by openmosix** [comment]
@stefanoc @andreacfm I created a branch tor-block-with-cache on API and deployed on the staging env. While it's working, I cannot tell if we have improved on performance - while hitting the endpoint with ab I get

{"message":"Take it easy and slow down","reset_in":41}

so I can't really execute a before/after test. It seems once in a while the connection gets stucked. 
@taganaka thoughts?

**Comment by taganaka** [comment]
The throttling system is kicking in.
From a benchmark standpoint it is safe to ignore any non-200 responses.

Throttled requests will be reported as `Non-2xx responses` but the overall `Requests per second` will be consistent and valid.

`ab -c 10 -n 500` should not be aggressive enough to trigger  throttling

**Comment by openmosix** [comment]
@taganaka @stefanoc @andreacfm I deployed on staging the branch with Stefano's changes (https://github.com/gild/tuna-api/tree/tor-block-with-cache) and tested with and without it.

I used the ab -c 10 -n 500 config above, hitting the termonuclear endpoint (no rails, just rack), in the 3 subsequent tests (after unicorn warmup)

Without this patch:

Requests per second:    49.63 [#/sec] (mean)
Requests per second:    51.94 [#/sec] (mean)
Requests per second:    48.73 [#/sec] (mean)


With the patch:

Requests per second:    52.02 [#/sec] (mean)
Requests per second:    50.46 [#/sec] (mean)
Requests per second:    52.41 [#/sec] (mean)

There is a slight improvement, but I'm not sure how statistically significant that is. Anyway, given it's not having a negative impact we could put it on prod and see if newrelic feels better?

**Comment by andreacfm** [comment]
I agree to go to prod. I am not expecting this branch will increase the
performance in a significant way. What I hope is that this will prevent us
to suffer from possible lag in the ip revolver.
Looks like for some reason the internal cache does not work properly.

On Tue, Jul 14, 2015 at 8:30 AM, Luca Bonmassar <notifications@github.com>
wrote:

> @taganaka <https://github.com/taganaka> @stefanoc
> <https://github.com/stefanoc> @andreacfm <https://github.com/andreacfm> I
> deployed on staging the branch with Stefano's changes (
> https://github.com/gild/tuna-api/tree/tor-block-with-cache) and tested
> with and without it.
>
> I used the ab -c 10 -n 500 config above, hitting the termonuclear endpoint
> (no rails, just rack), in the 3 subsequent tests (after unicorn warmup)
>
> Without this patch:
>
> Requests per second: 49.63 #/sec <http://mean>
> Requests per second: 51.94 #/sec <http://mean>
> Requests per second: 48.73 #/sec <http://mean>
>
> With the patch:
>
> Requests per second: 52.02 #/sec <http://mean>
> Requests per second: 50.46 #/sec <http://mean>
> Requests per second: 52.41 #/sec <http://mean>
>
> There is a slight improvement, but I'm not sure how statistically
> significant that is. Anyway, given it's not having a negative impact we
> could put it on prod and see if newrelic feels better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Gild/rack-tor-block/pull/2#issuecomment-121143861>.
>



-- 
*Andrea Campolonghi*
Lead Web Developer | Gild, Inc.
andrea@gild.com
+390236743864

Via Borsieri 41
20159 Milano Italy
www.gild.com

**Pull request merged**
